### ISSUE TITLE
Microsites box background issue on mobile

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_microsites#379] opened 2023-04-19 15:40 UTC
Hopefully a quick fix @msayoung @stephen-cox 

On https://site1.demo.microsites.localgovdrupal.org, mobile view, text on the box outs is overflowing the background colour

![Image](https://user-images.githubusercontent.com/708140/233128550-fe1b3e67-80bb-4769-b05a-498ae2c13253.png)

![Image](https://user-images.githubusercontent.com/708140/233128587-ac5abd09-5ad9-44c8-b833-3233f71f8183.png)

**Comment by msayoung** [comment] 2023-04-19 16:07
can you confirm it resolves itself with a refresh @willguv ? 
I think I know the cause

**Comment by willguv** [comment] 2023-04-19 18:41
Yes a refresh fixes this @msayoung 

<img width="485" alt="Screenshot 2023-04-19 at 19 40 08" src="https://user-images.githubusercontent.com/708140/233169671-46b2d3f6-e3ae-4af6-af2f-95e8395315a0.png">

**Comment by msayoung** [comment] 2023-04-20 08:20
@markconroy have you solved this elsewhere? - I think its caused by the equalheights js.

**Comment by markconroy** [comment] 2023-04-21 14:17
Yeah, I think we needed to setTimeout to give the page time to load before we started equalising things.

**Comment by RyanFH257** [comment] 2023-04-27 16:04
Hi team,

I've found more examples of this and a few other things that don't display well on mobile

Footers
![Screenshot_20230427-163555](https://user-images.githubusercontent.com/84503265/234920727-e7d50c0d-a934-4f43-93e0-a4abb4fd6f10.png)

![Screenshot_20230427-163950](https://user-images.githubusercontent.com/84503265/234920783-ec62849e-ffc3-4e74-9bdc-741ed58de2fe.png)

**Comment by RyanFH257** [comment] 2023-04-27 16:07
Header logo missing

![Screenshot_20230427-170600](https://user-images.githubusercontent.com/84503265/234921459-3e5da302-b46a-4265-bcd4-383b840a33e8.png)

Header logo small

![Screenshot_20230427-164043](https://user-images.githubusercontent.com/84503265/234921584-e1550661-f051-4346-a06d-9386ba9ee4c0.png)

**Comment by RyanFH257** [comment] 2023-04-27 16:08
Events image small

![Screenshot_20230427-163923](https://user-images.githubusercontent.com/84503265/234921835-f50d9923-11c1-4912-95ba-0de843c51e5b.png)

**Comment by RyanFH257** [comment] 2023-04-27 16:09
Footer logo small

![Screenshot_20230427-163839](https://user-images.githubusercontent.com/84503265/234922201-e72f2c42-3a23-4fb8-8bee-932c089706ca.png)

**Comment by RyanFH257** [comment] 2023-04-27 16:11
Media with text not responsive

![Screenshot_20230427-163726](https://user-images.githubusercontent.com/84503265/234923231-5059a079-7bf5-4ee6-84fc-9736a845a289.png)

![Screenshot_20230427-163829](https://user-images.githubusercontent.com/84503265/234923363-517ffcba-1137-446c-9052-e1e8e3e8e81d.png)

![Screenshot_20230427-163820](https://user-images.githubusercontent.com/84503265/234923459-47f470bc-ea4a-45ab-a35f-c50d41dbb8dc.png)

![Screenshot_20230427-163904](https://user-images.githubusercontent.com/84503265/234923573-b5afce50-33e7-4db3-a461-e29a2dd997a6.png)

**Comment by finnlewis** [comment] 2023-06-21 13:39
@markconroy might you have time to look at this one? Assigning to you for now in case you can or at least offer guidance on preferred approach. Thank you!

**Comment by kiwimind** [comment] 2023-07-17 08:34
There was a PR merged recently by @markconroy that sorted out the responsiveness of the footer columns, I'm planning on picking up some of the other issues raised.

**Comment by willguv** [comment] 2024-06-26 14:16
@markconroy @kiwimind is there any more work to do on this please? Thanks

**Comment by kiwimind** [comment] 2024-06-26 15:02
@willguv sorry, I'm not on LGD stuff at the moment so will remove my name from the assignees. I hope @markconroy can answer your questions.

**Comment by markconroy** [comment] 2024-06-26 15:44
Hi @willguv 

I'll have a check on this once we are calmed down on elections - I might even get to it tomorrow if we've no elections stable blockers with my name assigned.

**Comment by willguv** [comment] 2024-06-26 15:50
Cheers Mark

**Closed as completed** 2024-12-09 15:24 UTC
