### ISSUE TITLE
Add 'filter by title' to the content list view

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_microsites#449] opened 2024-05-28 10:53 UTC
A change made by @markconroy for the Love Essex website

Content designers needed to be able to search for their work by name

**Comment by stephen-cox** [comment] 2024-05-28 11:04
PR for this here: https://github.com/localgovdrupal/localgov_microsites_group/pull/446

It needs some work as we need to decide how we're applying changes to the views configuration.

**Comment by markconroy** [comment] 2024-05-31 06:37
Let's close this as it's a duplicate of https://github.com/localgovdrupal/localgov_microsites_group/pull/445

**Closed as completed by markconroy** 2024-05-31 06:37 UTC
Labels: Essex
